# analise de texto

In [1]:
# importando as bíbliotecas
import spacy
import pandas as pd 
from collections import Counter

In [5]:
#carreca os modelo em portugues 
nlp = spacy.load("pt_core_news_lg")

#carrega o texto do arquivo .txt
with open("texto.txt", "r", encoding="utf-8") as arquivo:
    texto = arquivo.read()

# processa o texto 
doc = nlp(texto)

In [ ]:
# listas onde informações serão armazenadas 
dados = []

# percorre todas os tokens
for token in doc:

    # ingnora pontuação e espaços
    if token.is_punct or token.is_space:
        continue

    # armazena as informações na lista
    dados.append({
        "Palavra" : token.text
        ,
        "lemma": token.lemma_,
        "classe" : token.pos_,
        "datalhe" : token.tag_
    })

In [11]:
# cria o dataframe com as informações
df = pd.DataFrame(dados)
df

        Palavra        lemma classe datalhe
0             O            o    DET     DET
1       governo      governo   NOUN    NOUN
2           dos         de o    ADP     ADP
3       Estados      Estados  PROPN   PROPN
4        Unidos       Unidos  PROPN   PROPN
5       colocou      colocar   VERB    VERB
6            em           em    ADP     ADP
7         vigor        vigor   NOUN    NOUN
8            um           um    DET     DET
9          novo         novo    ADJ     ADJ
10     tarifaço     tarifaço   NOUN    NOUN
11           de           de    ADP     ADP
12           25           25    NUM     NUM
13        sobre        sobre    ADP     ADP
14     diversos      diverso    DET     DET
15     produtos      produto   NOUN    NOUN
16   importados     importar   VERB    VERB
17           do         de o    ADP     ADP
18       Brasil       Brasil  PROPN   PROPN
19           Em           em    ADP     ADP
20     resposta     resposta   NOUN    NOUN
21     imediata     imediato    ADJ     ADJ
22            o            o    DET     DET
23   presidente   presidente   NOUN    NOUN
24         Lula         Lula  PROPN   PROPN
25     anunciou     anunciar   VERB    VERB
26           um           um    DET     DET
27       pacote       pacote   NOUN    NOUN
28           de           de    ADP     ADP
29        ajuda        ajuda   NOUN    NOUN
30           de           de    ADP     ADP
31           R$           R$    SYM     SYM
32         13,5         13,5    NUM     NUM
33      bilhões       bilhão    NUM     NUM
34      voltado       voltar   VERB    VERB
35         para         para  SCONJ   SCONJ
36      amparar      amparar   VERB    VERB
37           as            o    DET     DET
38   indústrias    indústria   NOUN    NOUN
39    nacionais     nacional    ADJ     ADJ
40  diretamente  diretamente    ADV     ADV
41     afetadas       afetar   VERB    VERB
42        pelas        por o    ADP     ADP
43        novas         novo    ADJ     ADJ
44        taxas         taxa   NOUN    NOUN
45   americanas    americano    ADJ     ADJ

In [12]:
df["classe"].value_counts()

classe
NOUN     10
ADP       9
DET       6
VERB      6
ADJ       5
PROPN     4
NUM       3
SYM       1
SCONJ     1
ADV       1
Name: count, dtype: int64

In [18]:
# frequencia das palavras 
frequencia = Counter(
    token.lemma_.lower()
    for token in doc
    if not token.is_punct
    and not token.is_space
    and not token.is_stop
)

df_freq = pd.DataFrame(frequencia.items(), columns=["Palavras", "Contagem"])
df_freq.sort_values("Contagem", ascending=False).head(20)

      Palavras  Contagem
0      governo         1
1      estados         1
2       unidos         1
3      colocar         1
4        vigor         1
5     tarifaço         1
6           25         1
7      diverso         1
8      produto         1
9     importar         1
10      brasil         1
11    resposta         1
12    imediato         1
13  presidente         1
14        lula         1
15    anunciar         1
16      pacote         1
17       ajuda         1
18          r$         1
19        13,5         1